### ISSUE TITLE
When Copying from Excel, "Copy" Selection is Reset

### ISSUE THREAD

**Issue by foigus** [hisaac/PlainPasta#2]
When Plain Pasta is not running and I copy or cut a cell in Excel, the chasing "marquee" border around the cell remains and copy and cut operations act as expected.

When Plain Pasta is running and I copy or cut a cell in Excel, the chasing "marquee" border reverts to a plain border in about a second.  This is similar to the effect if I had pressed the "Escape" key after the copy/cut action when Plain Pasta isn't running.  When performing a "copy" the issue isn't as great, but in the case of a "cut" the selected cell is not cleared upon the "paste" action.

Notably Excel may be doing some strange things here because the "cut" operation in Excel leaves the cell contents static until the the cell is "pasted" into another cell.

macOS 10.14.6, Excel 16.40 with a 365 license.

**Comment by hisaac** [comment]
Thank you for the bug report @foigus! This is a weird one. Do you think you could provide a short screen recording showing the behavior you're describing?

**Comment by foigus** [comment]
[Try this](https://www.dropbox.com/s/hmfmzxal1xyd9uk/PlainPasta_Excel.mp4?dl=0)--note I used the Ribbon's cut and copy commands for visual effect, but the effect is the same with the keyboard commands.

**Comment by hisaac** [comment]
Awesome, that video is really helpful. I'll take a look at this. Hopefully it's something I can address. 👍

**Comment by hisaac** [comment]
It looks like this is not something I will be able to fix. The marquee border that Excel uses when you've copied content gets reverted to a plain border whenever I call `clearContents()` on the pasteboard. It is necessary for me to clear the contents of the pasteboard in order to add new content, so I can't work around that.

Regardless, thank you for the report, and keep them coming if you find any more bugs.
